# Generated by Django 3.1.7 on 2021-12-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=255)),
                ('ad_title', models.CharField(max_length=255)),
                ('ad_desc', models.CharField(max_length=255)),
                ('creator', models.IntegerField()),
            ],
        ),
    ]
