# Generated by Django 3.1.7 on 2021-12-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='creator',
            field=models.IntegerField(null=True),
        ),
    ]
