# Generated by Django 3.1.7 on 2021-12-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20211208_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
